# Copyright (c) Anish Acharya.
# Licensed under the MIT License
{
  "seed": 1,
  "data_config":
  {
    "data_set": "imdb",
    "shape":[28,28],

    "val_frac": 0,                    # Fraction of Train Data used for Validation
    "num_labels": 10,                 # Num of Labels in Dataset
    "num_channels": 1,                # Number of channels # in case of CV experiments

    "train_batch_size": 2,           # Mini Batch Size
    "num_clients": 10,               # Number of mini-batches

    "test_batch_size": 2048,          # Test Batch Size
  },

  "training_config":
  {
    "global_epochs": 10,                 # epochs
    "eval_freq": 128,             # Specify number of steps between train/test/val evaluation

    "optimizer_config":
      {
        "loss": "infoNCE",   # Contrastive Loss
        "loss_sampler": "top_loss",
        "init_sampling_frac": 0.1,

        "optimizer": "SGD",
        "lr0": 0.01,
        "momentum": 0.9,
        "reg": 0.0001,
        "nesterov": true,
        "amsgrad": false
      },
    "lrs_config":
      {
        "lrs": 'step',
        "milestones": [1,5,10],
        "step_size": 1,
        "gamma": 0.9
      },
    "learner_config":
      {
        "net": "lenet",
      },
  },

  "fine_tune_config":
    {

    }
}